INFO     2021-02-26 21:17:11.810 request id: app - uvicorn.main:serve - Started server process [57333]
INFO     2021-02-26 21:17:11.812 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2021-02-26 21:17:11.813 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2021-02-26 21:17:11.816 request id: app - uvicorn.main:startup - Uvicorn running on http://0.0.0.0:8009 (Press CTRL+C to quit)
INFO     2021-02-26 21:17:41.040 request id: None - __main__:customize_logger - Here Is Your Info Log
ERROR    2021-02-26 21:17:41.069 request id: app - uvicorn.protocols.http.httptools_impl:run_asgi - Exception in ASGI application

Traceback (most recent call last):

  File "/home/andrei/PycharmProjects/fastapi_full_stack/backend/app/app/config/logging_main.py", line 43, in <module>
    uvicorn.run(app, host="0.0.0.0", port=8009)
    │       │   └ <fastapi.applications.FastAPI object at 0x7f1d7eebaeb0>
    │       └ <function run at 0x7f1d796cedc0>
    └ <module 'uvicorn' from '/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/uvicorn/main.py", line 362, in run
    server.run()
    │      └ <function Server.run at 0x7f1d796f89d0>
    └ <uvicorn.main.Server object at 0x7f1d79496c10>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7f1d796f8a60>
    │    │                  └ <uvicorn.main.Server object at 0x7f1d79496c10>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x7f1d7808d700>
                   │   │    │      │    │        └ <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739a4b50>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x7f1d7808d790>
                   │   │    │      └ <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739a4b50>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('192.168.1.97', 8009), ...
                   │   └ <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739a4b50>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f1d794af370>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739a4b...
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('192.168.1.97', 8009), ...
                 │    └ <fastapi.applications.FastAPI object at 0x7f1d7eebaeb0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f1d794af370>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/fastapi/applications.py", line 146, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739a4b...
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('192.168.1.97', 8009), ...
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739a4b...
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('192.168.1.97', 8009), ...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f1d796fa130>
          └ <fastapi.applications.FastAPI object at 0x7f1d7eebaeb0>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f1d7399be50>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('192.168.1.97', 8009), ...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x7f1d796ead00>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f1d796fa130>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f1d739af040>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('192.168.1.97', 8009), ...
          │    └ <fastapi.routing.APIRouter object at 0x7f1d80ba9670>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x7f1d796ead00>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f1d739af040>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('192.168.1.97', 8009), ...
          │     └ <function Route.handle at 0x7f1d79a99550>
          └ <fastapi.routing.APIRoute object at 0x7f1d794a0370>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f1d739af040>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f1d739...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('192.168.1.97', 8009), ...
          │    └ <function request_response.<locals>.app at 0x7f1d79494940>
          └ <fastapi.routing.APIRoute object at 0x7f1d794a0370>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x7f1d739a4d30>
                     └ <function get_request_handler.<locals>.app at 0x7f1d794948b0>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/fastapi/routing.py", line 196, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x7f1d79abd160>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
                 │                 │         │       └ {'request': <starlette.requests.Request object at 0x7f1d739a4d30>}
                 │                 │         └ <function customize_logger at 0x7f1d79494820>
                 │                 └ <fastapi.dependencies.models.Dependant object at 0x7f1d794a0490>
                 └ <function run_in_threadpool at 0x7f1d79c483a0>
  File "/home/andrei/.virtualenvs/fastapi_full_stack/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
                 │    │                     │      └ (functools.partial(<function customize_logger at 0x7f1d79494820>, request=<starlette.requests.Request object at 0x7f1d739a4d3...
                 │    │                     └ <built-in method run of Context object at 0x7f1d739acf80>
                 │    └ <method 'run_in_executor' of 'uvloop.loop.Loop' objects>
                 └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None

  File "/home/andrei/PycharmProjects/fastapi_full_stack/backend/app/app/config/logging_main.py", line 37, in customize_logger
    a = 1 / 0

ZeroDivisionError: division by zero
INFO     2021-02-26 23:32:53.132 request id: app - uvicorn.main:shutdown - Shutting down
INFO     2021-02-26 23:32:53.241 request id: app - uvicorn.lifespan.on:shutdown - Waiting for application shutdown.
INFO     2021-02-26 23:32:53.244 request id: app - uvicorn.lifespan.on:shutdown - Application shutdown complete.
INFO     2021-02-26 23:32:53.245 request id: app - uvicorn.main:serve - Finished server process [57333]
